---
- name: Install code-server on Ubuntu
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Check if code-server is installed
      command: code-server --version
      register: code_server_installed
      ignore_errors: true        

    - name: Download code-server
      shell: |
        curl -fsSL https://code-server.dev/install.sh | sh
      when: code_server_installed is failed

    - name: Create the /home/ubuntu/.config/code-server directory if it doesn't exist
      file:
        path: /home/ubuntu/.config/code-server
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
        recurse: yes

    - name: Create systemd service for code-server
      copy:
        dest: /etc/systemd/system/code-server.service
        content: |
          [Unit]
          Description=Code Server
          After=nginx.service

          [Service]
          Type=simple
          User=ubuntu
          ExecStart=/usr/bin/code-server --port 9101 --auth none 
          WorkingDirectory=/home/ubuntu
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start code-server service
      systemd:
        name: code-server
        enabled: yes
        state: started