---
- name: Install tac-proxy and Node.js on Amazon Linux
  hosts: localhost
  connection: local
  become: no
  vars:
    ansible_user: ec2-user

  tasks:
    - name: Check if NVM_DIR is set by ~/.bashrc
      command: bash -c "source ~/.bashrc && echo $NVM_DIR"
      register: nvm_dir_output
      ignore_errors: yes

    - name: Installing nvm
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash      
      when: nvm_dir_output.stdout != "/home/ec2-user/.nvm"

    - name: Check if node is installed
      command: node -v
      register: node_installed
      ignore_errors: true        

    - name: Installing NodeJS LTS
      command: bash -c "source ~/.bashrc && nvm install --lts"
      when: node_installed is failed

