---
- name: Setup and deploy Flask application
  hosts: localhost
  become: yes
  vars:
    app_name: "server-tool"
    port: 8108
    app_folder: "/home/ec2-user/web-apps/{{ app_name }}"

  tasks:
    # - name: Install Python packages from requirements.txt
    #   become_user: ec2-user
    #   pip:
    #     requirements: "{{ app_folder }}/requirements.txt"

    - name: Install Python packages from requirements.txt
      become_user: ec2-user
      shell: |
        source ~/.bashrc
        pip install -r "{{ app_folder }}/requirements.txt"

    # - name: Create AWS SSM Parameters
    #   community.aws.aws_ssm_parameter_store:
    #     name: "/{{ lookup('env', 'PROJECT_ID') }}/server-tool/{{ item.key }}"
    #     value: "{{ item.value }}"
    #     type: SecureString
    #     overwrite: yes
    #   loop:
    #     - { key: "jwt_secret_key", value: "lkjsdfahladhdslds" }
    #     - { key: "password", value: "testtest" }

    - name: Create systemd service for Flask app
      copy:
        dest: /etc/systemd/system/{{ app_name }}.service
        content: |
          [Unit]
          Description=Flask App {{ app_name }}
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory={{ app_folder }}
          ExecStart=/bin/bash -c 'source /home/ec2-user/.bashrc && flask run --port {{ port }} --debug'
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to apply new service
      command: systemctl daemon-reload

    - name: Enable and start the Flask app service
      service:
        name: "{{ app_name }}"
        enabled: yes
        state: started

    - name: Copy Caddyfile
      copy:
        src: "{{ app_folder }}/{{ app_name }}.Caddyfile"
        dest: /etc/caddy/apps/{{ app_name }}.Caddyfile

    - name: Reload Caddy service
      service:
        name: caddy
        state: reloaded

    - name: Source .bashrc and run Python script
      become_user: ec2-user
      shell: |
        source /home/ec2-user/.bashrc && python ~/scripts/generate-app-urls.py
      args:
        executable: /bin/bash